spring.application.name=spring-keycloak
server.port=8089


springdoc.swagger-ui.oauth.client-id=springboot-be
springdoc.swagger-ui.oauth.client-secret=26D3YXp850Blw5WSEY69D2D1T2hWJGZa

realm=dive-dev
server-url=http://127.0.0.1:8081
client-id=admin-cli
grant-type=password
name=admin
password=admin


