spring.application.name=spring-keycloak
server.port=8089

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8081/realms/dive-dev

keycloak.auth-server-url=http://127.0.0.1:8081
keycloak.realm=dive-dev
keycloak.client-id=springboot-be
keycloak.client-secret=26D3YXp850Blw5WSEY69D2D1T2hWJGZa
keycloak.admin.username=admin
keycloak.admin.password=admin

#keycloak.auth-server-url=http://localhost:8081
#keycloak.realm=dive-dev
#keycloak.resource=springboot-be
#keycloak.credentials.secret=26D3YXp850Blw5WSEY69D2D1T2hWJGZa

#spring.security.oauth2.resourceserver.opaquetoken.client-id=quarkus-be
#spring.security.oauth2.resourceserver.opaquetoken.client-secret=9Jottcs1IGZQsjDARZPEd8nsAh5igedL
#spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=http://127.0.0.1:8081/realms/dive-dev/protocol/openid-connect/token/introspect


#springdoc.swagger-ui.oauth.client-id=springboot-be
#springdoc.swagger-ui.oauth.client-secret=26D3YXp850Blw5WSEY69D2D1T2hWJGZa

#keycloak.admin.username=admin
#keycloak.admin.password=admin
#keycloak.realm-url=http://localhost:8081/realms/dive-dev
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://127.0.0.1:8081/realms/dive-dev
